# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV['POSTGRES_HOST'] %>
  port:     <%= ENV['POSTGRES_PORT'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: courses_development

test:
  <<: *default
  database: courses_test

citest:
  adapter: postgresql
  username: runner
  pool: 5
  timeout: 5000
  port: 5432
  host: postgres
  database: courses_test

production:
  <<: *default
  database: courses_production
