# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26ccdecbbd2efd4fdd9b0748100305c30ab03e966015099f44e8e1559a1e49d7ef7eb8b8b063fe51763a7aca45cc32c0378f0fd793d1251187bdd83f02a6da1b

test:
  secret_key_base: f6b31ea1061f2c0f8b835a3339be542886d6e7b80de2f5fdcfb9a4ab94d41add0f466c71a4b045cafecad8809d6385a829e52d9d27db9b44dbe357166ebab40a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
